### ISSUE TITLE
部署成功进入用户页面后抛出 `__page undefined` 错误，无法获取到博客页面内容

### ISSUE THREAD

**Issue by DomeenoH** [gethexon/hexon#11]
部署成功进入用户页面后抛出错误，无法获取到文章内容
![image](https://user-images.githubusercontent.com/29730075/168307058-02cb8e4f-713f-4251-a4c6-cd2bf95fd4af.png)
![image](https://user-images.githubusercontent.com/29730075/168307242-b11430a6-064c-46ec-a6c0-37447125abb3.png)
左上方各操作选项能够正常工作

下面是安装向导截图和宝塔下的博客文件目录截图
![image](https://user-images.githubusercontent.com/29730075/168307415-f9300b4a-f406-4db4-a51d-05943bba3cae.png)
![image](https://user-images.githubusercontent.com/29730075/168307490-b5db48f4-5e71-46ca-bd65-dc47810f8306.png)

**Comment by YuJianghao** [comment]
使用 `hexo init` 新建一个博客，看看是否有相同的问题。

如果没有，还麻烦尝试找到最小重现，看看是哪个文章的什么结构会导致问题。

**Comment by DomeenoH** [comment]
使用 hexo init 新建博客是能够正常获取文章内容的……我尝试了两个hexo仓库都遇到了报错和无法读取文章的情况，我再确认一下具体是什么原因
![image](https://user-images.githubusercontent.com/29730075/168416608-caf53c41-ef35-4763-a696-57690f2acd2d.png)

**Comment by YuJianghao** [comment]
顺便问下，你的一些版本：

- hexo
- node
- npm or yarn or pnpm or else
- hexon

**Comment by DomeenoH** [comment]
- hexo: 6.2.0
- node: v17.9.0
- pnpm: 7.1.0
- hexon: 0.12.2

我好像发现问题了，`source`目录下除`_drafts`和`_posts`外的文件夹内的`index.md`会被识别为页面，我在其中有一个`404`文件夹，里面除了md文件外还有一个css文件，这似乎会导致hexon报错
![image](https://user-images.githubusercontent.com/29730075/168417198-8796b94e-78a4-4859-944d-a9e429748082.png)

**Comment by DomeenoH** [comment]
source文件夹根目录出现其它文件的情况下好像同样也会导致没法识别文章内容

**Comment by YuJianghao** [comment]
能判断这是 hexo 错误还是 hexon 错误么？404 文件夹下的 style.css 具体是怎么被使用的呢？

**Comment by DomeenoH** [comment]
应该是hexon的错误，请参考上一条评论
404文件夹中的css文件会在博客的404页面中被调用

**Comment by YuJianghao** [comment]
了解了，我晚些时候尝试下看看

**Comment by YuJianghao** [comment]
尝试修复了，请检查 [v0.12.3-0](https://github.com/gethexon/hexon/releases/tag/v0.12.3-0)

**Comment by DomeenoH** [comment]
> 尝试修复了，请检查 [v0.12.3-0](https://github.com/gethexon/hexon/releases/tag/v0.12.3-0)

能够正常访问博客内容了，感谢修复~
