### ISSUE TITLE
`https://<ip:port>/admin` 子路径下同端口访问

### ISSUE THREAD

**Issue by appotry** [gethexon/hexon#13]
开两个端口不够优雅。
ip/admin这样访问，反向代理时一个域名就可以搞定

**Comment by appotry** [comment]
另外整个npm打包的话，用起来更方便

**Comment by appotry** [comment]
nginx有端口转发，访问链接rewrite方法，npm包里面有没有类似的工具来实现了？ @YuJianghao

**Comment by YuJianghao** [comment]
> nginx有端口转发，访问链接rewrite方法，npm包里面有没有类似的工具来实现了？ @YuJianghao

没看懂你想找的是 npm 的哪种工具。「nginx有端口转发，访问链接rewrite方法」具体指什么？

**Comment by YuJianghao** [comment]
另外还想问下，为什么要使用「hexo 本地预览」当做博客服务，而不是生成静态文件然后部署到其他平台？

**Comment by appotry** [comment]
本地反向代理端口访问博客的作用是，https支持pwa,tls等特性，在上传之前本地预览验证一下。测试没有问题再正式上传到云端


nginx 访问链接rewrite功能指的是 好比 访问 **/admin ， nginx把这种链接转发到**/myadmin
这样类似的链接替换，转发到其它非80，443端口，等。可以实现很多功能

winwin2011 ***@***.***> 于2022年6月23日周四 12:47写道：

**Comment by appotry** [comment]
本地反向代理测试各种插件，文章编排格式，文章修订等等。在正式上传之前本地预览一下，防止错误内容上传到云端

winwin2011 ***@***.***> 于2022年6月23日周四 12:47写道：

**Comment by YuJianghao** [comment]
测试插件和预览更改看起来是个很好的需求。但是有个问题，这两个是如何做到身份验证的。如果没有身份验证，那预览端口永远开着么？安全问题是如何解决的？

**Comment by YuJianghao** [comment]
> nginx有端口转发，访问链接rewrite方法，npm包里面有没有类似的工具来实现了？ @YuJianghao


实现难度不在于 rewrite 而是在于后端数据问题。现在的后端是自己启动了单独的 hexo，如果想要公用端口，现在能想到的是作为 hexo 插件接入 hexo。而后者需要大量重写代码。

**Comment by appotry** [comment]
https://github.com/jaredly/hexo-admin 参考一下这个的实现？

winwin2011 ***@***.***> 于2022年6月24日周五 12:14写道：

**Comment by YuJianghao** [comment]
这个了解过。目前还是面临两个问题：

- 预览端口如何保证安全，hexo 自带的预览是没有权限控制的，所有人都可以看的到。
- 如果迁移到 hexo 插件，有很大的工作量

**Comment by appotry** [comment]
关于第一个，个人解决方法是反向代理的是否使用nginx的认证访问。本地验证时，直接使用端口也没关系，放到云端部署，就部署到nginx后面，使用nginx的认证

个人做了一个nginx docker https://github.com/appotry/nginx-purge-docker
参考配置
```

        # To add basic authentication to v2 use auth_basic setting.
        #这个是提示信息
        auth_basic "Please input password";
        #存放密码文件的路径
        auth_basic_user_file /etc/nginx/conf.d/cron.htpasswd;

```

winwin2011 ***@***.***> 于2022年6月25日周六 15:20写道：

**Comment by appotry** [comment]
另外，这个插件实现了访问认证   https://github.com/jaredly/hexo-admin ，或者参考这个的认证实现？

winwin2011 ***@***.***> 于2022年6月25日周六 15:20写道：

**Comment by YuJianghao** [comment]
感觉 nginx 的方案还是满意。倾向于想办法让这些验证由 hexo 提供。
