### ISSUE TITLE
运行报错ID `source/CNAME` has been used

### ISSUE THREAD

**Issue by YuJianghao** [gethexon/hexon#14]
错误信息：
WarehouseError: ID `source/CNAME` has been used

除了该错误，同时还会提醒

```
Error: ENOENT: no such file or directory, open 'sitemap_template.xml'
```

应该是文件读取问题，我检测过该文件实际存在。

**Comment by abctel** [comment]
> 错误信息： WarehouseError: ID `source/CNAME` has been used
> 
> 除了该错误，同时还会提醒
> 
> ```
> Error: ENOENT: no such file or directory, open 'sitemap_template.xml'
> ```
> 
> 应该是文件读取问题，我检测过该文件实际存在。

麻烦你了，以后我注意。

**Comment by YuJianghao** [comment]
<img width="270" alt="image" src="https://user-images.githubusercontent.com/17293034/175210449-f1795ab6-d761-4637-9a39-87aa062879a2.png">

CNAME 文件内容是 `yujianghao.cn`。没能复现。有几个问题：

- 报错是哪里报错？页面弹窗还是控制台，可以截图么？
- 你的文件结构是什么样子的？重点是 `CNAME` 和 `sitemap_template.xml`
- 能找到是哪个文件引起的么？这样才能重现问题。
