### ISSUE TITLE
中文文档支持

### ISSUE THREAD

**Issue by GuaiJieYo** [gethexon/hexon#15]
为什么没用中文文档啊(恼
对于我这种英文不太好的人 不太友好哦qwq

**Comment by YuJianghao** [comment]
哈哈，因为懒

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 怪杰唷 ***@***.***>
发送时间: Thursday, June 23, 2022 7:50:36 PM
收件人: gethexon/hexon ***@***.***>
抄送: Subscribed ***@***.***>
主题: [gethexon/hexon] 为什么没用中文文档啊(恼 (Issue #15)


为什么没用中文文档啊(恼
对于我这种英文不太好的人 不太友好哦qwq

―

**Comment by YuJianghao** [comment]
如果方便，欢迎提供翻译 PR ~
