### ISSUE TITLE
当使用hexo-theme-aurora该主题时，不能查询列表，不能新增文章、页面、草稿，期待大大修复

### ISSUE THREAD

**Issue by 18-Xtreme** [gethexon/hexon#19]
无法查询文章列表

![Screenshot 2022-10-14 at 00-08-13 Hexon](https://user-images.githubusercontent.com/57245056/195648842-449ffc0d-d681-41fe-bdd8-521be66e3c78.png)

无法创建文章

![Screenshot 2022-10-14 at 00-08-52 Hexon](https://user-images.githubusercontent.com/57245056/195649066-56b430f6-6150-4999-b074-a91f34461824.png)

如果把主题换成简单类型的就没问题🤔 @YuJianghao

**Comment by 18-Xtreme** [comment]
http请求日子看上去没啥问题 数量能统计

<img width="855" alt="WeChat438c69d1ad4f26dc0e404f93fe5803d7" src="https://user-images.githubusercontent.com/57245056/195758132-72c28b09-8436-4db0-a104-4b281a8061b0.png">

另外几个bug：
1.图片加载404 实际上图片在博客上能显示

<img width="1090" alt="WeChata0a8df54b7071d54c0157b09ec788747" src="https://user-images.githubusercontent.com/57245056/195758345-af8fee47-0eb5-4caf-8202-d4c1489a0bc7.png">

2.修改文章的时间改成24小时制 有些时候会影响到文章排序 

大概看了下应该是 dayjs这个库格式化的时候需要将：

const DEFAULT_DATE_FORMAT = "YYYY-MM-DD hh:mm:ss.SSS"
改成
const DEFAULT_DATE_FORMAT = "YYYY-MM-DD HH:mm:ss.SSS"

这个log的时间，另外文章的时间不太清楚在哪😂

![1665719500196](https://user-images.githubusercontent.com/57245056/195758563-c134b1d3-64bd-40eb-9d53-26879a3b7c22.jpg)

**Comment by YuJianghao** [comment]
hexo-theme-aurora 主题的问题没能复现。我的 hexo 信息：

```txt
hexo-cli: 4.3.0
os: darwin 21.3.0 12.2

node: 16.15.0
v8: 9.4.146.24-node.20
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.4
openssl: 1.1.1n+quic
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```

`hexon@0.12.5`

`hexo-theme-aurora@1.5.5`

**Comment by YuJianghao** [comment]
其他的 bug 新开 issue 吧
