### ISSUE TITLE
建议：为程序添加后台运行功能及意外退出自启动功能

### ISSUE THREAD

**Issue by foxhank** [gethexon/hexon#24]
成功部署到设备，但是我一关闭终端程序就关了，网页端会显示‘未发送任何数据’。
我希望能为程序加入后台运行功能（可以通过systemctl之类），实现开机自启，单行命令运行（不用先cd到程序目录然后mnpm），或者守护程序实现意外停止自动恢复。

**Comment by YuJianghao** [comment]
可以使用 pm2 守护程序

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: foxhank ***@***.***>
发送时间: Wednesday, March 29, 2023 1:35:43 AM
收件人: gethexon/hexon ***@***.***>
抄送: Subscribed ***@***.***>
主题: [gethexon/hexon] 建议：为程序添加后台运行功能及意外退出自启动功能 (Issue #24)


成功部署到设备，但是我一关闭终端程序就关了，网页端会显示‘未发送任何数据’。
我希望能为程序加入后台运行功能（可以通过systemctl之类），实现开机自启，单行命令运行（不用先cd到程序目录然后mnpm），或者守护程序实现意外停止自动恢复。

―
