### ISSUE TITLE
使用 aurora 主題時，pages 請求內的各 page 的 __page 屬性不會設定上去

### ISSUE THREAD

**Issue by konnokai** [gethexon/hexon#33]
# 錯誤說明

使用 Hexo 內建的 `landscape` 主題請求 `http://localhost:4000/proxy/hexo/pages` 時正常
![image](https://user-images.githubusercontent.com/4331068/232746375-6a5087fd-6bf6-4773-b997-db09355f1669.png)

當主題改用 `aurora` 後 `__page` 屬性消失
![image](https://user-images.githubusercontent.com/4331068/232746563-afc4eebe-7034-4161-99f5-6be34e3945d5.png)

網頁顯示的錯誤訊息
![20230418_181031_chrome](https://user-images.githubusercontent.com/4331068/232746662-55c9c3bf-35e6-4ca3-900f-facbda0f9ff2.png)

且在建立新的 page 時 Hexo 會出現錯誤 (這個錯誤不管使用 `landscape` 或是 `aurora` 主題都會出現，但使用 `landscape` 主題的話重整頁面後 page 會出現在網頁上)
![image](https://user-images.githubusercontent.com/4331068/232747107-3f672ab4-08a8-4b58-8256-a5c66adde038.png)

# 已知情況
使用 `aurora` 主題時，`src\server\services\hexo-service.ts#L253` 中的 `docs` 跟 `res` 變數已無 `__page` 屬性
![image](https://user-images.githubusercontent.com/4331068/232751715-9403e0a2-18bd-42d9-8c9b-d380aa9975ca.png)

不使用 `.map(toPage)` 直接輸出 `hexo.locals.get("pages")` 的情況亦同
![image](https://user-images.githubusercontent.com/4331068/232753345-fbf3bddc-4938-4b1e-b6a3-b3e8f194473f.png)

# 猜測
`aurora` 主題在 generate 階段時將某個東西給移除掉了，或是沒有把 `__page` 屬性補上

# 備註
由於 `aurora` 主題原作者已停止開發，目前本人有自行 fork 該專案修改，也會追查此問題的導致的原因跟協助處理

# 使用版本
- hexo: 6.3.0
- hexo-cli: 4.3.0
- os: Windows 10 Pro x64 (但這問題在我實際部屬的伺服器上也會發生，伺服器: Debian GNU/Linux 11 (bullseye) x86_64)
- node: 16.20.0
- aurora: 1.5.5 [本人修改的版本](https://github.com/konnokai/hexo-theme-aurora)

**Comment by YuJianghao** [comment]
@konnokai 在 #41 用 Server patch 修复了一下。如果可以最好了，如果不行就得采用 Client 修复了。
