### ISSUE TITLE
无法配置（路径错误）

### ISSUE THREAD

**Issue by AkiCCLing** [gethexon/hexon#42]
![image](https://github.com/gethexon/hexon/assets/53488343/4e008547-ae21-4a2f-a662-f5f88724fdd8)
![image](https://github.com/gethexon/hexon/assets/53488343/5a8ed0f3-45e5-42ac-a8e9-e6415ebebc16)

OS : Windows 10

**Comment by YuJianghao** [comment]
不太了解 Windows 下的路径如何工作的。相对路径可以工作么？`../blog`

**Comment by AkiCCLing** [comment]
> 不太了解 Windows 下的路径如何工作的。相对路径可以工作么？`../blog`

相对路径正常，感谢解答
