### ISSUE TITLE
密码忘了用户名也忘了怎么办

### ISSUE THREAD

**Issue by cyf-maple** [gethexon/hexon#47]
好几个月没用想起来还有个blog，用户名和密码都记不得了，有哪里能看默认用户名吗？

**Comment by YuJianghao** [comment]
-  😢 当前用户名还得手动看 `/hexon/server/data/common.db`
- 有一个[重置密码](https://github.com/gethexon/hexon/blob/bb95fb28afec81b62c8d5f2ffd7e177bdfb7ec91/README_CN.md#-%E5%91%BD%E4%BB%A4)的命令：`pnpm resetpwd`
