### ISSUE TITLE
Hexo使用solitude主题后无法正确读取Hexo版本

### ISSUE THREAD

**Issue by ClassmateShen** [gethexon/hexon#50]
如题，我的Hexo版本是7.2.0，但一旦使用solitude主题后就会提示版本过低，但如果用默认的landscape就不会有问题

**Comment by YuJianghao** [comment]
hexon 目前用的是 `hexo@^5.4.2`。版本该更新了。

**Comment by ClassmateShen** [comment]
没修复啊，还是不行，麻烦佬再看看

**Comment by YuJianghao** [comment]
是 hexon 该更新了，不是你该更新了 😄

**Comment by YuJianghao** [comment]
fixed by d99aa1c23504adf7fc9afee51e07f17de3655341
