### ISSUE TITLE
feat: template for frontmatters

### ISSUE THREAD

**Issue by asplun** [gethexon/hexon#6]
再不同主题下，会自定义一些frontmatters项，每次都要重新输入相当麻烦。建议加入保存参数项，或者保存自定义的内容

例如我就有很多
---
title:
date:
updated:
tags:
categories:
keywords:
description:
top_img:
comments:
cover:
toc:
toc_number:
toc_style_simple:
copyright:
copyright_author:
copyright_author_href:
copyright_url:
copyright_info:
mathjax:
katex:
aplayer:
highlight_shrink:
aside:
---

**Comment by YuJianghao** [comment]
see https://github.com/gethexon/hexon/releases/tag/v0.10.0
